In [1]:
import numpy as np
import gym
import random
import time
import IPython.display as clear_output



In [2]:
# ### Creating the environment
# We will using the environment *FrozenLake-v0*

In [3]:
# ### Creating the environment
# We will using the environment *FrozenLake-v0*

 ### Creating the environment
 We will using the environment *FrozenLake-v0*

In [4]:
env = gym.make("FrozenLake-v0")


In [5]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size, action_space_size))
print(q_table)



[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [6]:
num_episodes = 1000
max_steps_per_episode = 100

learning_rate = 0.01            # Alpha
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.01


In [7]:
num_episodes = 1000
max_steps_per_episode = 100

learning_rate = 0.01            # Alpha
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.01


 ###  Implement Reinforcement learning

 ### Initializing Q-learning parameters
 Now we initalize all the paramenters.
 ~num_episodes~ defines the total number of episodes

 ### Initializing Q-learning parameters
 Now we initalize all the paramenters.
 `num_episodes` defines the total number of episodes

 ### Initializing Q-learning parameters
 Now we initalize all the paramenters.
 `num_episodes` defines the total number of episodes

 ### Initializing Q-learning parameters
 Now we initalize all the paramenters.

 `num_episodes` defines the total number of episodes

 ### Creating the Q-table
 We are going to construct our Q-table, and initialize all the Q-values.
 number of rows in the table = size of state space in the environemnt
 number of columns is equivalent size of action space

 ### Creating the Q-table

 We are going to construct our Q-table, and initialize all the Q-values.
 number of rows in the table = size of state space in the environemnt
 number of columns is equivalent size of action space

 ### Creating the Q-table
 We are going to construct our Q-table, and initialize all the Q-values.

 number of rows in the table = size of state space in the environemnt

 number of columns is equivalent size of action space

 ### Initializing Q-learning parameters
 Now we initalize all the paramenters.

 `num_episodes` defines the total number of episodes

 `learning_rate` is represented with the simple $\alpha$

 ### Initializing Q-learning parameters
 Now we initalize all the paramenters.

 `num_episodes` defines the total number of episodes

 `learning_rate` is represented with the simple $\x$

 ### Initializing Q-learning parameters
 Now we initalize all the paramenters.

 `num_episodes` defines the total number of episodes

 `learning_rate` is represented with the simple $\alpha$

 ### Initializing Q-learning parameters
 Now we initalize all the paramenters.

 `num_episodes` defines the total number of episodes

 `learning_rate` is represented with the symbol $\alpha$
 `discount_rate` is represented with the symbol $\gama$
 `exploration_rate` is represented with the symbol $\epsilon$

 ### Initializing Q-learning parameters
 Now we initalize all the paramenters.

 `num_episodes` defines the total number of episodes

 `learning_rate` is represented with the symbol $\alpha$

 `discount_rate` is represented with the symbol $\gama$

 `exploration_rate` is represented with the symbol $\epsilon$

In [8]:
num_episodes = 1000
max_steps_per_episode = 100 # we define a maximum number of steps that our agent is allowed to take within a single episode

learning_rate = 0.01            # Alpha
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.01


In [9]:
num_episodes = 1000
max_steps_per_episode = 100 # we define a maximum number of steps that our agent is allowed to take within a single episode

learning_rate = 0.01            # Alpha
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001


In [10]:
rewards_all_episodes = []

# Q-learning
for episode in range(num_episodes):
    state = env.reset()

    done = False
    rewards_current_episode = 0  # The start rewards
    for step in range(max_steps_per_episode):

        # Exploration-exploitation trade-off
        exploration_rate_threshold = random.uniform(0, 1)
        # this will determine whether our agent will explore or expoit
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state, :])
        else:
            action = env.action_space.sample()

        new_state, reward, done, info = env.step(action)

        # UPdate Q-table for Q(s,a)
        q_table[state, action] = q_table[state, action] * (1-learning_rate) + learning_rate*(
            reward + discount_rate * np.max(q_table[new_state, :]))

        # Transition to the next state
        state = new_state
        rewards_current_episode += reward

        if done == True:
            break

        # Exploration rate decay
        exploration_rate = min_exploration_rate + \
            (max_exploration_rate - min_exploration_rate) * \
            np.exp(-exploration_decay_rate * episode)

        rewards_all_episodes.append(rewards_current_episode)

# Calculate and print the a erage reward per thousand episodes
rewards_per_thousand_episodes = np.split( \
    np.array(rewards_all_episodes),num_episodes/1000)
count = 1000

print("*********Average reward per thousand episodes *******\n")
for r in rewards_per_thousand_episodes:
    print(count, ":", str(sum(r/1000)))
    count += 1000

print("\n\n**********************Q-table*******************\n")
print(q_table)



*********Average reward per thousand episodes *******

1000 : 0.0


**********************Q-table*******************

[[4.91350135e-06 1.63298277e-05 5.45024853e-06 5.51908838e-06]
 [2.23441894e-06 7.80418808e-06 3.81740849e-06 2.87157357e-05]
 [4.38199326e-05 1.00277518e-04 3.12087539e-05 3.60027130e-06]
 [2.78448330e-06 3.32686601e-06 6.55530237e-07 1.33578093e-05]
 [7.78253345e-06 2.51609806e-05 9.65676700e-06 2.01824821e-06]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.71010661e-04 9.75261101e-04 2.24269093e-04 2.59517778e-07]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [3.23666991e-06 1.05813039e-04 2.43941573e-05 1.88629637e-05]
 [6.55499809e-05 3.41647565e-04 1.11567747e-03 7.69324471e-05]
 [1.14819021e-02 8.87548135e-04 2.90676356e-03 5.70879626e-06]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.25130590e-04 1.07524328e-03 8.48413804e-03 1.82586838e-03]


In [11]:
rewards_all_episodes = []

# Q-learning
for episode in range(num_episodes):
    state = env.reset()

    done = False
    rewards_current_episode = 0  # The start rewards
    for step in range(max_steps_per_episode):

        # Exploration-exploitation trade-off
        exploration_rate_threshold = random.uniform(0, 1)
        # this will determine whether our agent will explore or expoit
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state, :])
        else:
            action = env.action_space.sample()

        new_state, reward, done, info = env.step(action)

        # UPdate Q-table for Q(s,a)
        q_table[state, action] = q_table[state, action] * (1-learning_rate) + learning_rate*(
            reward + discount_rate * np.max(q_table[new_state, :]))

        # Transition to the next state
        state = new_state
        rewards_current_episode += reward

        if done == True:
            break

        # Exploration rate decay
        exploration_rate = min_exploration_rate + \
            (max_exploration_rate - min_exploration_rate) * \
            np.exp(-exploration_decay_rate * episode)

        rewards_all_episodes.append(rewards_current_episode)

# Calculate and print the a erage reward per thousand episodes
rewards_per_thousand_episodes = np.split( \
    np.array(rewards_all_episodes),num_episodes/1000)
count = 1000

print("*********Average reward per thousand episodes *******\n")
for r in rewards_per_thousand_episodes:
    print(count, ":", str(sum(r)))
    count += 1000

print("\n\n**********************Q-table*******************\n")
print(q_table)



*********Average reward per thousand episodes *******

1000 : 0.0


**********************Q-table*******************

[[3.17689734e-04 6.39720322e-04 3.66470448e-04 3.29861485e-04]
 [1.47251794e-04 2.73615597e-04 3.39833038e-04 8.14194771e-04]
 [8.65939325e-04 2.03362887e-03 7.02204555e-04 2.21796443e-04]
 [1.23821836e-04 1.01602693e-04 2.02511323e-05 4.99453288e-04]
 [4.13104699e-04 8.57035734e-04 2.87825296e-04 1.52567451e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.09607388e-03 8.13867869e-03 1.55034835e-03 8.02583398e-05]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [2.90006744e-04 3.30167714e-03 7.80572022e-04 9.84501361e-04]
 [2.35310533e-03 1.35319995e-02 3.38845293e-03 1.86823409e-03]
 [3.59047060e-02 1.31923809e-02 1.31106694e-02 3.42358122e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.21328253e-03 8.98377395e-03 3.78101956e-02 8.24297293e-03]


In [12]:
rewards_all_episodes = []

# Q-learning
for episode in range(num_episodes):
    state = env.reset()

    done = False
    rewards_current_episode = 0  # The start rewards
    for step in range(max_steps_per_episode):

        # Exploration-exploitation trade-off
        exploration_rate_threshold = random.uniform(0, 1)
        # this will determine whether our agent will explore or expoit
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state, :])
        else:
            action = env.action_space.sample()

        new_state, reward, done, info = env.step(action)

        # UPdate Q-table for Q(s,a)
        q_table[state, action] = q_table[state, action] * (1-learning_rate) + learning_rate*(
            reward + discount_rate * np.max(q_table[new_state, :]))

        # Transition to the next state
        state = new_state
        rewards_current_episode += reward

        if done == True:
            break

        # Exploration rate decay
        exploration_rate = min_exploration_rate + \
            (max_exploration_rate - min_exploration_rate) * \
            np.exp(-exploration_decay_rate * episode)

        rewards_all_episodes.append(rewards_current_episode)


In [13]:
print(rewards_all_episodes)
# Calculate and print the a erage reward per thousand episodes
rewards_per_thousand_episodes = np.split( \
    np.array(rewards_all_episodes),num_episodes/1000)
count = 1000

print("*********Average reward per thousand episodes *******\n")
for r in rewards_per_thousand_episodes:
    print(count, ":", str(sum(r)))
    count += 1000

print("\n\n**********************Q-table*******************\n")
print(q_table)



[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,

In [14]:
rewards_all_episodes = []

# Q-learning
for episode in range(num_episodes):
    state = env.reset()

    done = False
    rewards_current_episode = 0  # The start rewards
    for step in range(max_steps_per_episode):

        # Exploration-exploitation trade-off
        exploration_rate_threshold = random.uniform(0, 1)
        # this will determine whether our agent will explore or expoit
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state, :])
        else:
            action = env.action_space.sample()

        new_state, reward, done, info = env.step(action)

        # UPdate Q-table for Q(s,a)
        q_table[state, action] = q_table[state, action] * (1-learning_rate) + learning_rate*(
            reward + discount_rate * np.max(q_table[new_state, :]))

        # Transition to the next state
        state = new_state
        rewards_current_episode += reward
        print(reward)

        if done == True:
            break

        # Exploration rate decay
        exploration_rate = min_exploration_rate + \
            (max_exploration_rate - min_exploration_rate) * \
            np.exp(-exploration_decay_rate * episode)

        rewards_all_episodes.append(rewards_current_episode)


0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0


In [15]:
rewards_all_episodes = []

# Q-learning
for episode in range(num_episodes):
    state = env.reset()

    done = False
    rewards_current_episode = 0  # The start rewards
    for step in range(max_steps_per_episode):

        # Exploration-exploitation trade-off
        exploration_rate_threshold = random.uniform(0, 1)
        # this will determine whether our agent will explore or expoit
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state, :])
            print(action)
        else:
            action = env.action_space.sample()

        new_state, reward, done, info = env.step(action)

        # UPdate Q-table for Q(s,a)
        q_table[state, action] = q_table[state, action] * (1-learning_rate) + learning_rate*(
            reward + discount_rate * np.max(q_table[new_state, :]))

        # Transition to the next state
        state = new_state
        rewards_current_episode += reward

        if done == True:
            break

        # Exploration rate decay
        exploration_rate = min_exploration_rate + \
            (max_exploration_rate - min_exploration_rate) * \
            np.exp(-exploration_decay_rate * episode)

        rewards_all_episodes.append(rewards_current_episode)


1
0
1
1
1
1
1
1
0
1
1
1
3
0
1
1
1
3
1
3
1
1
0
3
0
1
1
0
1
1
0
1
1
1
3
1
1
1
1
0
3
2
1
1
1
3
1
2
0
1
1
1
1
1
1
1
1
3
1
0
3
3
1
3
1
1
3
1
1
0
1
3
1
0
3
0
0
1
3
1
1
1
3
3
1
1
3
1
3
1
1
0
1
1
3
1
1
1
1
1
1
1
1
0
3
3
3
3
1
1
2
1
1
1
1
1
3
1
0
1
1
1
1
1
1
1
0
1
0
0
1
3
1
0
1
3
1
0
1
3
1
1
1
1
3
3
1
1
1
1
1
1
1
1
1
1
0
1
1
1
1
1
0
1
1
3
1
1
1
1
1
3
1
1
1
1
1
1
1
1
3
1
0
1
1
3
1
0
1
1
1
1
1
3
1
3
1
0
1
0
1
1
1
0
1
1
1
2
1
1
3
1
3
1
0
1
1
1
3
1
3
1
3
1
0
1
1
1
3
1
1
3
1
1
3
1
0
1
1
1
3
1
0
2
2
1
1
1
3
1
1
1
3
3
3
3
1
3
3
1
3
1
0
0
1
0
1
2
1
3
1
1
3
1
1
3
3
1
1
0
3
1
3
1
1
3
1
1
3
3
3
1
1
1
3
3
1
1
1
0
1
1
1
1
3
1
3
3
3
1
1
3
3
1
1
0
0
0
0
0
0
1
1
1
0
2
3
1
1
0
0
1
3
3
1
1
3
1
3
1
1
1
1
1
3
3
1
1
3
3
3
3
0
1
1
0
1
0
1
1
0
1
0
0
1
0
1
0
1
3
1
1
1
1
3
1
1
1
1
1
0
0
1
1
0
1
0
0
0
0
0
1
1
1
1
1
0
0
1
1
0
1
1
1
3
1
1
0
1
1
1
1
1
1
3
3
3
0
1
1
1
1
1
1
1
0
0
3
0
1
0
1
1
0
1
1
1
1
0
3
3
1
1
0
1
1
0
0
1
0
1
0
3
1
3
1
3
3
1
3
1
1
1
1
1
1
0
1
3
0
0
0
1
0
0
1
1
1
0
0
1
1
3
1
3
1
1
1
1
1
1
1
1
1
0
1
1
1
1
1


In [16]:
rewards_all_episodes = []

# Q-learning
for episode in range(num_episodes):
    state = env.reset()

    done = False
    rewards_current_episode = 0  # The start rewards
    for step in range(max_steps_per_episode):

        # Exploration-exploitation trade-off
        exploration_rate_threshold = random.uniform(0, 1)
        # this will determine whether our agent will explore or expoit
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state, :])
        else:
            action = env.action_space.sample()
            print(action)

        new_state, reward, done, info = env.step(action)

        # UPdate Q-table for Q(s,a)
        q_table[state, action] = q_table[state, action] * (1-learning_rate) + learning_rate*(
            reward + discount_rate * np.max(q_table[new_state, :]))

        # Transition to the next state
        state = new_state
        rewards_current_episode += reward

        if done == True:
            break

        # Exploration rate decay
        exploration_rate = min_exploration_rate + \
            (max_exploration_rate - min_exploration_rate) * \
            np.exp(-exploration_decay_rate * episode)

        rewards_all_episodes.append(rewards_current_episode)


3
1
1
2
0
0
3
0
2
3
3
3
1
2
2
3
3
0
2
1
2
3
1
2
0
0
3
1
0
3
3
1
2
2
1
0
2
3
2
3
0
0
3
1
1
2
0
1
0
3
1
1
3
1
3
3
1
0
0
0
1
1
1
1
2
1
2
3
1
1
0
3
1
3
0
1
3
1
3
3
1
2
0
0
1
1
1
3
2
2
3
2
1
1
1
1
0
2
3
3
0
0
1
3
1
0
0
2
2
0
3
3
0
3
3
0
1
0
0
2
3
3
0
1
3
2
1
3
2
0
3
1
3
0
1
1
2
2
2
2
3
3
1
2
0
1
0
2
3
3
2
3
1
3
3
2
2
3
0
0
1
3
1
3
1
1
3
3
0
3
0
2
2
3
2
2
1
3
1
3
0
1
3
3
1
3
3
3
1
2
1
3
2
3
1
0
0
3
1
0
3
0
2
2
3
0
0
3
0
1
0
3
1
0
0
0
3
2
1
0
3
2
3
2
1
3
0
3
1
2
1
0
1
2
3
3
0
0
0
0
1
2
2
3
0
3
0
0
3
1
2
2
2
1
2
1
1
2
1
0
2
2
0
1
3
0
3
2
0
1
1
3
1
2
3
3
1
3
0
2
1
0
0
0
2
2
3
3
3
0
0
1
3
2
1
2
0
0
3
2
2
1
3
0
1
3
3
3
2
0
0
1
2
1
3
1
3
2
1
1
1
1
2
2
2
2
1
3
0
0
0
2
0
1
0
3
2
1
3
1
3
3
1
1
0
2
3
2
3
0
0
3
3
1
1
0
2
1
0
0
3
1
2
2
1
0
2
3
1
1
1
3
0
2
3
2
2
2
0
2
2
2
0
2
3
3
3
1
3
1
3
0
2
2
3
3
2
3
0
3
0
1
1
3
1
1
0
2
3
2
1
2
3
3
2
1
0
0
0
3
0
1
1
1
1
0
0
1
0
1
1
2
3
2
0
3
1
2
0
3
1
1
2
1
1
3
0
2
2
2
2
1
0
2
2
3
1
2
1
1
1
3
0
0
1
0
0
3
1
1
1
3
1
1
3
0
0
1
0
3
0
3
0
1
2
3
3
2
1
3
2
0
2
2
3
0
3
2
1
2


In [17]:
rewards_all_episodes = []

# Q-learning
for episode in range(num_episodes):
    state = env.reset()

    done = False
    rewards_current_episode = 0  # The start rewards
    for step in range(max_steps_per_episode):

        # Exploration-exploitation trade-off
        exploration_rate_threshold = random.uniform(0, 1)
        # this will determine whether our agent will explore or expoit
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state, :])
        else:
            action = env.action_space.sample()

        new_state, reward, done, info = env.step(action)
        print(reward)

        # UPdate Q-table for Q(s,a)
        q_table[state, action] = q_table[state, action] * (1-learning_rate) + learning_rate*(
            reward + discount_rate * np.max(q_table[new_state, :]))

        # Transition to the next state
        state = new_state
        rewards_current_episode += reward

        if done == True:
            break

        # Exploration rate decay
        exploration_rate = min_exploration_rate + \
            (max_exploration_rate - min_exploration_rate) * \
            np.exp(-exploration_decay_rate * episode)

        rewards_all_episodes.append(rewards_current_episode)


0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0


In [18]:
rewards_all_episodes = []

# Q-learning
for episode in range(num_episodes):
    state = env.reset()

    done = False
    rewards_current_episode = 0  # The start rewards
    for step in range(max_steps_per_episode):

        # Exploration-exploitation trade-off
        exploration_rate_threshold = random.uniform(0, 1)
        # this will determine whether our agent will explore or expoit
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state, :])
        else:
            action = env.action_space.sample()

        new_state, reward, done, info = env.step(action)
        print(new_state)

        # UPdate Q-table for Q(s,a)
        q_table[state, action] = q_table[state, action] * (1-learning_rate) + learning_rate*(
            reward + discount_rate * np.max(q_table[new_state, :]))

        # Transition to the next state
        state = new_state
        rewards_current_episode += reward

        if done == True:
            break

        # Exploration rate decay
        exploration_rate = min_exploration_rate + \
            (max_exploration_rate - min_exploration_rate) * \
            np.exp(-exploration_decay_rate * episode)

        rewards_all_episodes.append(rewards_current_episode)


4
0
4
5
4
5
1
0
0
0
4
0
1
5
1
2
2
2
2
6
7
0
0
0
0
0
1
0
1
0
1
5
1
5
1
2
3
3
7
1
1
2
1
1
1
2
1
1
5
0
4
0
1
1
2
2
2
3
7
0
4
4
5
0
0
0
0
4
0
1
1
2
3
2
2
6
10
6
10
11
4
8
12
0
1
1
0
4
5
0
0
0
0
4
4
8
4
0
0
0
1
5
4
4
0
0
0
0
0
0
0
1
2
1
1
0
0
0
0
0
1
2
1
1
5
0
4
8
12
0
1
0
0
4
8
4
4
8
9
13
13
14
15
1
0
4
0
0
1
1
0
0
4
5
4
0
0
0
0
0
4
4
0
1
2
3
3
7
4
8
8
4
5
1
1
5
0
1
1
0
4
5
0
4
5
1
5
1
1
0
0
0
0
0
1
2
2
1
2
2
1
0
1
2
6
10
11
0
4
8
12
0
0
4
5
4
0
1
0
0
0
1
5
4
4
0
0
0
1
2
3
7
4
8
8
8
9
10
6
2
2
1
1
1
2
3
2
2
3
2
2
2
3
3
7
0
1
2
3
3
2
2
3
3
3
2
1
2
3
7
1
1
5
0
0
4
8
8
8
12
0
1
0
0
4
5
1
1
1
0
0
4
0
4
5
1
5
0
0
0
4
8
9
8
4
0
1
0
0
1
5
0
0
1
1
2
3
3
3
3
2
3
7
0
0
1
5
1
1
5
1
5
0
4
8
9
13
14
13
9
10
6
5
4
5
0
0
0
1
0
0
1
0
0
4
8
8
9
5
0
0
1
1
0
0
1
2
6
5
4
4
5
1
5
0
0
4
8
4
8
4
4
5
0
4
8
9
8
12
1
0
4
4
0
4
0
0
0
0
4
4
5
4
5
4
5
0
4
0
0
0
0
1
5
1
5
0
4
5
1
1
0
0
1
2
6
5
1
2
2
1
5
0
4
8
4
8
12
1
2
6
5
4
0
0
0
1
2
1
0
0
0
1
5
4
5
0
0
0
4
5
0
0
0
4
8
9
8
12
1
5
1
5
0
0
0
0
0
4
5
4
4
5
0
0
0
4
8
8
9

In [21]:
rewards_all_episodes = []

# Q-learning
for episode in range(num_episodes):
    state = env.reset()

    done = False
    rewards_current_episode = 0  # The start rewards
    for step in range(max_steps_per_episode):

        # Exploration-exploitation trade-off
        exploration_rate_threshold = random.uniform(0, 1)
        # this will determine whether our agent will explore or expoit
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state, :])
        else:
            action = env.action_space.sample()

        new_state, reward, done, info = env.step(action)
        print(state, new_state, done, reward)

        # UPdate Q-table for Q(s,a)
        q_table[state, action] = q_table[state, action] * (1-learning_rate) + learning_rate*(
            reward + discount_rate * np.max(q_table[new_state, :]))

        # Transition to the next state
        state = new_state
        rewards_current_episode += reward

        if done == True:
            break

        # Exploration rate decay
        exploration_rate = min_exploration_rate + \
            (max_exploration_rate - min_exploration_rate) * \
            np.exp(-exploration_decay_rate * episode)

        rewards_all_episodes.append(rewards_current_episode)


0 0 False 0.0
0 1 False 0.0
1 5 True 0.0
0 0 False 0.0
0 0 False 0.0
0 4 False 0.0
4 8 False 0.0
8 12 True 0.0
0 0 False 0.0
0 1 False 0.0
1 5 True 0.0
0 1 False 0.0
1 2 False 0.0
2 6 False 0.0
6 5 True 0.0
0 0 False 0.0
0 0 False 0.0
0 0 False 0.0
0 0 False 0.0
0 1 False 0.0
1 0 False 0.0
0 0 False 0.0
0 1 False 0.0
1 1 False 0.0
1 5 True 0.0
0 1 False 0.0
1 2 False 0.0
2 6 False 0.0
6 2 False 0.0
2 6 False 0.0
6 5 True 0.0
0 4 False 0.0
4 4 False 0.0
4 8 False 0.0
8 4 False 0.0
4 0 False 0.0
0 4 False 0.0
4 0 False 0.0
0 4 False 0.0
4 4 False 0.0
4 0 False 0.0
0 1 False 0.0
1 1 False 0.0
1 1 False 0.0
1 5 True 0.0
0 0 False 0.0
0 0 False 0.0
0 0 False 0.0
0 4 False 0.0
4 4 False 0.0
4 4 False 0.0
4 0 False 0.0
0 1 False 0.0
1 2 False 0.0
2 1 False 0.0
1 0 False 0.0
0 1 False 0.0
1 0 False 0.0
0 1 False 0.0
1 5 True 0.0
0 0 False 0.0
0 4 False 0.0
4 5 True 0.0
0 0 False 0.0
0 4 False 0.0
4 5 True 0.0
0 1 False 0.0
1 1 False 0.0
1 5 True 0.0
0 4 False 0.0
4 4 False 0.0
4 0 False 0.0
0 

In [22]:
rewards_all_episodes = []

# Q-learning
for episode in range(num_episodes):
    state = env.reset()
    print("new episodes")

    done = False
    rewards_current_episode = 0  # The start rewards
    for step in range(max_steps_per_episode):

        # Exploration-exploitation trade-off
        exploration_rate_threshold = random.uniform(0, 1)
        # this will determine whether our agent will explore or expoit
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state, :])
        else:
            action = env.action_space.sample()

        new_state, reward, done, info = env.step(action)
        print(state, new_state, done, reward)

        # UPdate Q-table for Q(s,a)
        q_table[state, action] = q_table[state, action] * (1-learning_rate) + learning_rate*(
            reward + discount_rate * np.max(q_table[new_state, :]))

        # Transition to the next state
        state = new_state
        rewards_current_episode += reward

        if done == True:
            break

        # Exploration rate decay
        exploration_rate = min_exploration_rate + \
            (max_exploration_rate - min_exploration_rate) * \
            np.exp(-exploration_decay_rate * episode)

        rewards_all_episodes.append(rewards_current_episode)


new episodes
0 0 False 0.0
0 0 False 0.0
0 1 False 0.0
1 0 False 0.0
0 4 False 0.0
4 5 True 0.0
new episodes
0 0 False 0.0
0 1 False 0.0
1 1 False 0.0
1 2 False 0.0
2 2 False 0.0
2 3 False 0.0
3 2 False 0.0
2 3 False 0.0
3 3 False 0.0
3 7 True 0.0
new episodes
0 4 False 0.0
4 0 False 0.0
0 0 False 0.0
0 0 False 0.0
0 0 False 0.0
0 1 False 0.0
1 2 False 0.0
2 1 False 0.0
1 5 True 0.0
new episodes
0 0 False 0.0
0 4 False 0.0
4 5 True 0.0
new episodes
0 0 False 0.0
0 1 False 0.0
1 1 False 0.0
1 5 True 0.0
new episodes
0 0 False 0.0
0 4 False 0.0
4 5 True 0.0
new episodes
0 4 False 0.0
4 4 False 0.0
4 4 False 0.0
4 4 False 0.0
4 8 False 0.0
8 12 True 0.0
new episodes
0 0 False 0.0
0 0 False 0.0
0 4 False 0.0
4 4 False 0.0
4 5 True 0.0
new episodes
0 0 False 0.0
0 1 False 0.0
1 1 False 0.0
1 0 False 0.0
0 0 False 0.0
0 0 False 0.0
0 1 False 0.0
1 1 False 0.0
1 1 False 0.0
1 5 True 0.0
new episodes
0 1 False 0.0
1 5 True 0.0
new episodes
0 0 False 0.0
0 1 False 0.0
1 5 True 0.0
new episodes


In [23]:
num_episodes = 10
# we define a maximum number of steps that our agent is allowed to take within a single episode
max_steps_per_episode = 100

# Alpha the weighted for sum of old value and learned value in Q
learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001


In [24]:
# Calculate and print the a erage reward per thousand episodes
rewards_per_thousand_episodes = np.split(
    np.array(rewards_all_episodes), num_episodes/1000)
count = 1000

print("*********Average reward per thousand episodes *******\n")
for r in rewards_per_thousand_episodes:
    print(count, ":", str(sum(r/1000)))
    count += 1000

print("\n\n**********************Q-table*******************\n")
print(q_table)


ValueError: array split does not result in an equal division

In [25]:
rewards_all_episodes = []

# Q-learning
for episode in range(num_episodes):
    state = env.reset()
    print("new episodes")

    done = False
    rewards_current_episode = 0  # The start rewards
    for step in range(max_steps_per_episode):

        # Exploration-exploitation trade-off
        exploration_rate_threshold = random.uniform(0, 1)
        # this will determine whether our agent will explore or expoit
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state, :])
        else:
            action = env.action_space.sample()

        new_state, reward, done, info = env.step(action)
        print(state, new_state, done, reward)

        # UPdate Q-table for Q(s,a)
        q_table[state, action] = q_table[state, action] * (1-learning_rate) + learning_rate*(
            reward + discount_rate * np.max(q_table[new_state, :]))

        # Transition to the next state
        state = new_state
        rewards_current_episode += reward

        if done == True:
            break

        # Exploration rate decay
        exploration_rate = min_exploration_rate + \
            (max_exploration_rate - min_exploration_rate) * \
            np.exp(-exploration_decay_rate * episode)

        rewards_all_episodes.append(rewards_current_episode)


new episodes
0 1 False 0.0
1 0 False 0.0
0 0 False 0.0
0 0 False 0.0
0 0 False 0.0
0 0 False 0.0
0 1 False 0.0
1 2 False 0.0
2 2 False 0.0
2 1 False 0.0
1 0 False 0.0
0 0 False 0.0
0 4 False 0.0
4 0 False 0.0
0 4 False 0.0
4 4 False 0.0
4 0 False 0.0
0 0 False 0.0
0 0 False 0.0
0 0 False 0.0
0 0 False 0.0
0 1 False 0.0
1 2 False 0.0
2 1 False 0.0
1 1 False 0.0
1 1 False 0.0
1 1 False 0.0
1 1 False 0.0
1 1 False 0.0
1 0 False 0.0
0 4 False 0.0
4 0 False 0.0
0 1 False 0.0
1 5 True 0.0
new episodes
0 4 False 0.0
4 8 False 0.0
8 12 True 0.0
new episodes
0 0 False 0.0
0 0 False 0.0
0 0 False 0.0
0 0 False 0.0
0 1 False 0.0
1 5 True 0.0
new episodes
0 0 False 0.0
0 0 False 0.0
0 0 False 0.0
0 4 False 0.0
4 0 False 0.0
0 4 False 0.0
4 5 True 0.0
new episodes
0 0 False 0.0
0 4 False 0.0
4 8 False 0.0
8 8 False 0.0
8 12 True 0.0
new episodes
0 0 False 0.0
0 0 False 0.0
0 0 False 0.0
0 0 False 0.0
0 1 False 0.0
1 2 False 0.0
2 3 False 0.0
3 3 False 0.0
3 3 False 0.0
3 3 False 0.0
3 2 False 0.0
2

In [26]:
num_episodes = 10
# we define a maximum number of steps that our agent is allowed to take within a single episode
max_steps_per_episode = 100

# Alpha the weighted for sum of old value and learned value in Q
learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001


In [27]:
num_episodes = 10
# we define a maximum number of steps that our agent is allowed to take within a single episode
max_steps_per_episode = 500

# Alpha the weighted for sum of old value and learned value in Q
learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001


In [28]:
rewards_all_episodes = []

# Q-learning
for episode in range(num_episodes):
    state = env.reset()
    print("new episodes")

    done = False
    rewards_current_episode = 0  # The start rewards
    for step in range(max_steps_per_episode):

        # Exploration-exploitation trade-off
        exploration_rate_threshold = random.uniform(0, 1)
        # this will determine whether our agent will explore or expoit
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state, :])
        else:
            action = env.action_space.sample()

        new_state, reward, done, info = env.step(action)
        print(state, new_state, done, reward)

        # UPdate Q-table for Q(s,a)
        q_table[state, action] = q_table[state, action] * (1-learning_rate) + learning_rate*(
            reward + discount_rate * np.max(q_table[new_state, :]))

        # Transition to the next state
        state = new_state
        rewards_current_episode += reward

        if done == True:
            break

        # Exploration rate decay
        exploration_rate = min_exploration_rate + \
            (max_exploration_rate - min_exploration_rate) * \
            np.exp(-exploration_decay_rate * episode)

        rewards_all_episodes.append(rewards_current_episode)


new episodes
0 4 False 0.0
4 8 False 0.0
8 9 False 0.0
9 8 False 0.0
8 4 False 0.0
4 5 True 0.0
new episodes
0 1 False 0.0
1 1 False 0.0
1 5 True 0.0
new episodes
0 1 False 0.0
1 1 False 0.0
1 5 True 0.0
new episodes
0 0 False 0.0
0 0 False 0.0
0 0 False 0.0
0 0 False 0.0
0 1 False 0.0
1 5 True 0.0
new episodes
0 0 False 0.0
0 0 False 0.0
0 0 False 0.0
0 0 False 0.0
0 0 False 0.0
0 1 False 0.0
1 2 False 0.0
2 3 False 0.0
3 3 False 0.0
3 7 True 0.0
new episodes
0 0 False 0.0
0 0 False 0.0
0 4 False 0.0
4 4 False 0.0
4 5 True 0.0
new episodes
0 4 False 0.0
4 5 True 0.0
new episodes
0 0 False 0.0
0 0 False 0.0
0 0 False 0.0
0 0 False 0.0
0 0 False 0.0
0 0 False 0.0
0 4 False 0.0
4 0 False 0.0
0 0 False 0.0
0 4 False 0.0
4 5 True 0.0
new episodes
0 4 False 0.0
4 5 True 0.0
new episodes
0 0 False 0.0
0 0 False 0.0
0 0 False 0.0
0 4 False 0.0
4 8 False 0.0
8 9 False 0.0
9 10 False 0.0
10 9 False 0.0
9 13 False 0.0
13 12 True 0.0


In [29]:
rewards_all_episodes = []

# Q-learning
for episode in range(num_episodes):
    state = env.reset()
    print("episodes:", episode)

    done = False
    rewards_current_episode = 0  # The start rewards
    for step in range(max_steps_per_episode):

        # Exploration-exploitation trade-off
        exploration_rate_threshold = random.uniform(0, 1)
        # this will determine whether our agent will explore or expoit
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state, :])
        else:
            action = env.action_space.sample()

        new_state, reward, done, info = env.step(action)
        print(state, new_state, done, reward)

        # UPdate Q-table for Q(s,a)
        q_table[state, action] = q_table[state, action] * (1-learning_rate) + learning_rate*(
            reward + discount_rate * np.max(q_table[new_state, :]))

        # Transition to the next state
        state = new_state
        rewards_current_episode += reward

        if done == True:
            break

        # Exploration rate decay
        exploration_rate = min_exploration_rate + \
            (max_exploration_rate - min_exploration_rate) * \
            np.exp(-exploration_decay_rate * episode)

        rewards_all_episodes.append(rewards_current_episode)


episodes: 0
0 0 False 0.0
0 0 False 0.0
0 1 False 0.0
1 1 False 0.0
1 1 False 0.0
1 2 False 0.0
2 2 False 0.0
2 6 False 0.0
6 5 True 0.0
episodes: 1
0 4 False 0.0
4 4 False 0.0
4 8 False 0.0
8 4 False 0.0
4 5 True 0.0
episodes: 2
0 1 False 0.0
1 0 False 0.0
0 0 False 0.0
0 0 False 0.0
0 1 False 0.0
1 0 False 0.0
0 1 False 0.0
1 2 False 0.0
2 6 False 0.0
6 2 False 0.0
2 1 False 0.0
1 2 False 0.0
2 2 False 0.0
2 6 False 0.0
6 5 True 0.0
episodes: 3
0 0 False 0.0
0 4 False 0.0
4 4 False 0.0
4 4 False 0.0
4 4 False 0.0
4 0 False 0.0
0 4 False 0.0
4 8 False 0.0
8 12 True 0.0
episodes: 4
0 1 False 0.0
1 0 False 0.0
0 0 False 0.0
0 4 False 0.0
4 0 False 0.0
0 0 False 0.0
0 0 False 0.0
0 0 False 0.0
0 1 False 0.0
1 5 True 0.0
episodes: 5
0 4 False 0.0
4 4 False 0.0
4 0 False 0.0
0 4 False 0.0
4 8 False 0.0
8 4 False 0.0
4 8 False 0.0
8 8 False 0.0
8 4 False 0.0
4 8 False 0.0
8 4 False 0.0
4 4 False 0.0
4 5 True 0.0
episodes: 6
0 0 False 0.0
0 1 False 0.0
1 1 False 0.0
1 2 False 0.0
2 3 False 0

In [30]:
rewards_all_episodes = []

# Q-learning
for episode in range(num_episodes):
    state = env.reset()
    print("episodes:", episode)

    done = False
    rewards_current_episode = 0  # The start rewards
    for step in range(max_steps_per_episode):

        # Exploration-exploitation trade-off
        exploration_rate_threshold = random.uniform(0, 1)
        # this will determine whether our agent will explore or expoit
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state, :])
        else:
            action = env.action_space.sample()

        new_state, reward, done, info = env.step(action)
        print(state, new_state, done, reward)

        # UPdate Q-table for Q(s,a)
        q_table[state, action] = q_table[state, action] * (1-learning_rate) + learning_rate*(
            reward + discount_rate * np.max(q_table[new_state, :]))

        # Transition to the next state
        state = new_state
        rewards_current_episode += reward

        if done == True:
            break

        # Exploration rate decay
        exploration_rate = min_exploration_rate + \
            (max_exploration_rate - min_exploration_rate) * \
            np.exp(-exploration_decay_rate * episode)

        rewards_all_episodes.append(rewards_current_episode)


episodes: 0
0 4 False 0.0
4 4 False 0.0
4 4 False 0.0
4 8 False 0.0
8 9 False 0.0
9 5 True 0.0
episodes: 1
0 4 False 0.0
4 4 False 0.0
4 8 False 0.0
8 12 True 0.0
episodes: 2
0 0 False 0.0
0 1 False 0.0
1 5 True 0.0
episodes: 3
0 4 False 0.0
4 0 False 0.0
0 1 False 0.0
1 0 False 0.0
0 4 False 0.0
4 0 False 0.0
0 0 False 0.0
0 4 False 0.0
4 5 True 0.0
episodes: 4
0 1 False 0.0
1 1 False 0.0
1 0 False 0.0
0 0 False 0.0
0 0 False 0.0
0 1 False 0.0
1 2 False 0.0
2 6 False 0.0
6 5 True 0.0
episodes: 5
0 0 False 0.0
0 0 False 0.0
0 0 False 0.0
0 0 False 0.0
0 4 False 0.0
4 8 False 0.0
8 12 True 0.0
episodes: 6
0 0 False 0.0
0 0 False 0.0
0 0 False 0.0
0 0 False 0.0
0 0 False 0.0
0 4 False 0.0
4 8 False 0.0
8 9 False 0.0
9 8 False 0.0
8 8 False 0.0
8 8 False 0.0
8 4 False 0.0
4 8 False 0.0
8 8 False 0.0
8 4 False 0.0
4 4 False 0.0
4 4 False 0.0
4 8 False 0.0
8 4 False 0.0
4 0 False 0.0
0 0 False 0.0
0 1 False 0.0
1 2 False 0.0
2 6 False 0.0
6 10 False 0.0
10 9 False 0.0
9 13 False 0.0
13 14 F

In [31]:
num_episodes = 100
# we define a maximum number of steps that our agent is allowed to take within a single episode
max_steps_per_episode = 100

# Alpha the weighted for sum of old value and learned value in Q
learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001


In [32]:
rewards_all_episodes = []

# Q-learning
for episode in range(num_episodes):
    state = env.reset()
    print("episodes:", episode)

    done = False
    rewards_current_episode = 0  # The start rewards
    for step in range(max_steps_per_episode):

        # Exploration-exploitation trade-off
        exploration_rate_threshold = random.uniform(0, 1)
        # this will determine whether our agent will explore or expoit
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state, :])
        else:
            action = env.action_space.sample()

        new_state, reward, done, info = env.step(action)
        print(state, new_state, done, reward)

        # UPdate Q-table for Q(s,a)
        q_table[state, action] = q_table[state, action] * (1-learning_rate) + learning_rate*(
            reward + discount_rate * np.max(q_table[new_state, :]))

        # Transition to the next state
        state = new_state
        rewards_current_episode += reward

        if done == True:
            break

        # Exploration rate decay
        exploration_rate = min_exploration_rate + \
            (max_exploration_rate - min_exploration_rate) * \
            np.exp(-exploration_decay_rate * episode)

        rewards_all_episodes.append(rewards_current_episode)


episodes: 0
0 4 False 0.0
4 4 False 0.0
4 8 False 0.0
8 8 False 0.0
8 12 True 0.0
episodes: 1
0 0 False 0.0
0 0 False 0.0
0 0 False 0.0
0 0 False 0.0
0 4 False 0.0
4 4 False 0.0
4 4 False 0.0
4 4 False 0.0
4 8 False 0.0
8 4 False 0.0
4 8 False 0.0
8 12 True 0.0
episodes: 2
0 0 False 0.0
0 0 False 0.0
0 4 False 0.0
4 4 False 0.0
4 4 False 0.0
4 5 True 0.0
episodes: 3
0 0 False 0.0
0 1 False 0.0
1 1 False 0.0
1 0 False 0.0
0 1 False 0.0
1 0 False 0.0
0 1 False 0.0
1 2 False 0.0
2 6 False 0.0
6 10 False 0.0
10 6 False 0.0
6 2 False 0.0
2 1 False 0.0
1 5 True 0.0
episodes: 4
0 0 False 0.0
0 1 False 0.0
1 0 False 0.0
0 0 False 0.0
0 0 False 0.0
0 1 False 0.0
1 2 False 0.0
2 6 False 0.0
6 10 False 0.0
10 9 False 0.0
9 5 True 0.0
episodes: 5
0 0 False 0.0
0 0 False 0.0
0 0 False 0.0
0 0 False 0.0
0 4 False 0.0
4 5 True 0.0
episodes: 6
0 1 False 0.0
1 5 True 0.0
episodes: 7
0 0 False 0.0
0 4 False 0.0
4 0 False 0.0
0 4 False 0.0
4 8 False 0.0
8 9 False 0.0
9 5 True 0.0
episodes: 8
0 1 False 0.

In [33]:
num_episodes = 1000
# we define a maximum number of steps that our agent is allowed to take within a single episode
max_steps_per_episode = 100

# Alpha the weighted for sum of old value and learned value in Q
learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001


In [34]:
rewards_all_episodes = []

# Q-learning
for episode in range(num_episodes):
    state = env.reset()
    print("episodes:", episode)

    done = False
    rewards_current_episode = 0  # The start rewards
    for step in range(max_steps_per_episode):

        # Exploration-exploitation trade-off
        exploration_rate_threshold = random.uniform(0, 1)
        # this will determine whether our agent will explore or expoit
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state, :])
        else:
            action = env.action_space.sample()

        new_state, reward, done, info = env.step(action)
        print(state, new_state, done, reward)

        # UPdate Q-table for Q(s,a)
        q_table[state, action] = q_table[state, action] * (1-learning_rate) + learning_rate*(
            reward + discount_rate * np.max(q_table[new_state, :]))

        # Transition to the next state
        state = new_state
        rewards_current_episode += reward

        if done == True:
            break

        # Exploration rate decay
        exploration_rate = min_exploration_rate + \
            (max_exploration_rate - min_exploration_rate) * \
            np.exp(-exploration_decay_rate * episode)

        rewards_all_episodes.append(rewards_current_episode)


episodes: 0
0 1 False 0.0
1 0 False 0.0
0 0 False 0.0
0 1 False 0.0
1 2 False 0.0
2 6 False 0.0
6 5 True 0.0
episodes: 1
0 0 False 0.0
0 1 False 0.0
1 2 False 0.0
2 3 False 0.0
3 7 True 0.0
episodes: 2
0 4 False 0.0
4 5 True 0.0
episodes: 3
0 0 False 0.0
0 1 False 0.0
1 5 True 0.0
episodes: 4
0 4 False 0.0
4 0 False 0.0
0 1 False 0.0
1 1 False 0.0
1 5 True 0.0
episodes: 5
0 1 False 0.0
1 5 True 0.0
episodes: 6
0 0 False 0.0
0 0 False 0.0
0 0 False 0.0
0 1 False 0.0
1 0 False 0.0
0 0 False 0.0
0 1 False 0.0
1 2 False 0.0
2 3 False 0.0
3 3 False 0.0
3 2 False 0.0
2 1 False 0.0
1 5 True 0.0
episodes: 7
0 1 False 0.0
1 1 False 0.0
1 5 True 0.0
episodes: 8
0 1 False 0.0
1 5 True 0.0
episodes: 9
0 0 False 0.0
0 0 False 0.0
0 0 False 0.0
0 0 False 0.0
0 1 False 0.0
1 0 False 0.0
0 1 False 0.0
1 5 True 0.0
episodes: 10
0 4 False 0.0
4 8 False 0.0
8 8 False 0.0
8 9 False 0.0
9 5 True 0.0
episodes: 11
0 0 False 0.0
0 1 False 0.0
1 2 False 0.0
2 1 False 0.0
1 5 True 0.0
episodes: 12
0 4 False 0.0

In [35]:
print(q_table)
# Calculate and print the a erage reward per thousand episodes
rewards_per_thousand_episodes = np.split(
    np.array(rewards_all_episodes), num_episodes/1000)
count = 1000

print("*********Average reward per thousand episodes *******\n")
for r in rewards_per_thousand_episodes:
    print(count, ":", str(sum(r/1000)))
    count += 1000

print("\n\n**********************Q-table*******************\n")
print(q_table)


[[0.52738793 0.47795437 0.48021676 0.47322931]
 [0.25541515 0.28491707 0.29424836 0.42362916]
 [0.31528037 0.31644101 0.3089706  0.36500835]
 [0.23245927 0.24774397 0.23545459 0.33861937]
 [0.54297863 0.25076229 0.33644763 0.26593827]
 [0.         0.         0.         0.        ]
 [0.24116816 0.16005026 0.24738552 0.06409389]
 [0.         0.         0.         0.        ]
 [0.2723279  0.38714155 0.27720345 0.5734855 ]
 [0.47160124 0.66552236 0.29210411 0.35811221]
 [0.62499665 0.38386216 0.40975539 0.25506849]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.41100635 0.47495755 0.75452086 0.35510941]
 [0.64773955 0.9168779  0.74945468 0.69929766]
 [0.         0.         0.         0.        ]]
*********Average reward per thousand episodes *******

1000 : 0.0


**********************Q-table*******************

[[0.52738793 0.47795437 0.48021676 0.47322931]
 [0.25541515 0.28491707 0.29424836 0.42362916]
 [0.31528037 0.31644101 0.3089706  

In [36]:
rewards_all_episodes = []

# Q-learning
for episode in range(num_episodes):
    state = env.reset()
    print("episodes:", episode)

    done = False
    rewards_current_episode = 0  # The start rewards
    for step in range(max_steps_per_episode):

        # Exploration-exploitation trade-off
        exploration_rate_threshold = random.uniform(0, 1)
        # this will determine whether our agent will explore or expoit
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state, :])
        else:
            action = env.action_space.sample()

        new_state, reward, done, info = env.step(action)
        print(state, new_state, reward)

        # UPdate Q-table for Q(s,a)
        q_table[state, action] = q_table[state, action] * (1-learning_rate) + learning_rate*(
            reward + discount_rate * np.max(q_table[new_state, :]))

        # Transition to the next state
        state = new_state
        rewards_current_episode += reward

        if done == True:
            break

        # Exploration rate decay
        exploration_rate = min_exploration_rate + \
            (max_exploration_rate - min_exploration_rate) * \
            np.exp(-exploration_decay_rate * episode)

        rewards_all_episodes.append(rewards_current_episode)


episodes: 0
0 0 0.0
0 0 0.0
0 0 0.0
0 0 0.0
0 1 0.0
1 0 0.0
0 4 0.0
4 4 0.0
4 5 0.0
episodes: 1
0 0 0.0
0 0 0.0
0 0 0.0
0 0 0.0
0 4 0.0
4 8 0.0
8 9 0.0
9 13 0.0
13 13 0.0
13 9 0.0
9 8 0.0
8 4 0.0
4 4 0.0
4 4 0.0
4 0 0.0
0 0 0.0
0 1 0.0
1 1 0.0
1 0 0.0
0 0 0.0
0 4 0.0
4 4 0.0
4 0 0.0
0 4 0.0
4 4 0.0
4 5 0.0
episodes: 2
0 0 0.0
0 0 0.0
0 4 0.0
4 5 0.0
episodes: 3
0 1 0.0
1 0 0.0
0 0 0.0
0 4 0.0
4 5 0.0
episodes: 4
0 0 0.0
0 4 0.0
4 8 0.0
8 8 0.0
8 8 0.0
8 9 0.0
9 13 0.0
13 12 0.0
episodes: 5
0 0 0.0
0 0 0.0
0 1 0.0
1 1 0.0
1 2 0.0
2 2 0.0
2 1 0.0
1 5 0.0
episodes: 6
0 0 0.0
0 0 0.0
0 0 0.0
0 0 0.0
0 0 0.0
0 0 0.0
0 4 0.0
4 5 0.0
episodes: 7
0 1 0.0
1 1 0.0
1 1 0.0
1 0 0.0
0 0 0.0
0 4 0.0
4 5 0.0
episodes: 8
0 1 0.0
1 2 0.0
2 6 0.0
6 2 0.0
2 3 0.0
3 2 0.0
2 2 0.0
2 1 0.0
1 1 0.0
1 1 0.0
1 2 0.0
2 3 0.0
3 3 0.0
3 3 0.0
3 7 0.0
episodes: 9
0 4 0.0
4 4 0.0
4 0 0.0
0 4 0.0
4 5 0.0
episodes: 10
0 1 0.0
1 1 0.0
1 0 0.0
0 4 0.0
4 8 0.0
8 8 0.0
8 4 0.0
4 4 0.0
4 5 0.0
episodes: 11
0 4 0.0
4 8 0.0

In [37]:
# Calculate and print the a erage reward per thousand episodes
rewards_per_thousand_episodes = np.split(
    np.array(rewards_all_episodes), num_episodes/1000)
count = 1000

print("*********Average reward per thousand episodes *******\n")
for r in rewards_per_thousand_episodes:
    print(count, ":", str(sum(r/1000)))
    count += 1000

print("\n\n**********************Q-table*******************\n")
print(q_table)


*********Average reward per thousand episodes *******

1000 : 0.0


**********************Q-table*******************

[[0.53262639 0.50004396 0.51493095 0.50382742]
 [0.36556953 0.412294   0.35463159 0.48099169]
 [0.38541292 0.40051576 0.39967041 0.44173582]
 [0.31728644 0.2812601  0.24179813 0.42870357]
 [0.55624747 0.43158678 0.36051367 0.38688989]
 [0.         0.         0.         0.        ]
 [0.23025569 0.20647325 0.34585494 0.10011733]
 [0.         0.         0.         0.        ]
 [0.42533504 0.34456956 0.40662056 0.60524649]
 [0.52040307 0.67293223 0.58009831 0.44605577]
 [0.58783859 0.4248645  0.5033947  0.2820585 ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.49372533 0.43260195 0.79298263 0.19945446]
 [0.74503838 0.87474152 0.8445648  0.79371905]
 [0.         0.         0.         0.        ]]


In [38]:
# Calculate and print the a erage reward per thousand episodes
rewards_per_thousand_episodes = np.split(
    np.array(rewards_all_episodes), num_episodes/1000)
count = 1000
print(len(rewards_all_episodes))
print("*********Average reward per thousand episodes *******\n")
for r in rewards_per_thousand_episodes:
    print(count, ":", str(sum(r/1000)))
    count += 1000

print("\n\n**********************Q-table*******************\n")
print(q_table)


10708
*********Average reward per thousand episodes *******

1000 : 0.0


**********************Q-table*******************

[[0.53262639 0.50004396 0.51493095 0.50382742]
 [0.36556953 0.412294   0.35463159 0.48099169]
 [0.38541292 0.40051576 0.39967041 0.44173582]
 [0.31728644 0.2812601  0.24179813 0.42870357]
 [0.55624747 0.43158678 0.36051367 0.38688989]
 [0.         0.         0.         0.        ]
 [0.23025569 0.20647325 0.34585494 0.10011733]
 [0.         0.         0.         0.        ]
 [0.42533504 0.34456956 0.40662056 0.60524649]
 [0.52040307 0.67293223 0.58009831 0.44605577]
 [0.58783859 0.4248645  0.5033947  0.2820585 ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.49372533 0.43260195 0.79298263 0.19945446]
 [0.74503838 0.87474152 0.8445648  0.79371905]
 [0.         0.         0.         0.        ]]


In [39]:
# Calculate and print the a erage reward per thousand episodes
rewards_per_thousand_episodes = np.split(
    np.array(rewards_all_episodes), num_episodes/1000)
count = 1000
print(len(rewards_all_episodes))
print("*********Average reward per thousand episodes *******\n")
for r in rewards_per_thousand_episodes:
    print(rewards_all_episodes)
    print(count, ":", str(sum(r/1000)))
    count += 1000

print("\n\n**********************Q-table*******************\n")
print(q_table)


10708
*********Average reward per thousand episodes *******

[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0

In [40]:
# Calculate and print the a erage reward per thousand episodes
rewards_per_thousand_episodes = np.split(
    np.array(rewards_all_episodes), num_episodes/1000)
count = 1000
print(len(rewards_all_episodes))
print("*********Average reward per thousand episodes *******\n")
print(len(rewards_per_thousand_episodes))
for r in rewards_per_thousand_episodes:
    print(count, ":", str(sum(r/1000)))
    count += 1000

print("\n\n**********************Q-table*******************\n")
print(q_table)


10708
*********Average reward per thousand episodes *******

1
1000 : 0.0


**********************Q-table*******************

[[0.53262639 0.50004396 0.51493095 0.50382742]
 [0.36556953 0.412294   0.35463159 0.48099169]
 [0.38541292 0.40051576 0.39967041 0.44173582]
 [0.31728644 0.2812601  0.24179813 0.42870357]
 [0.55624747 0.43158678 0.36051367 0.38688989]
 [0.         0.         0.         0.        ]
 [0.23025569 0.20647325 0.34585494 0.10011733]
 [0.         0.         0.         0.        ]
 [0.42533504 0.34456956 0.40662056 0.60524649]
 [0.52040307 0.67293223 0.58009831 0.44605577]
 [0.58783859 0.4248645  0.5033947  0.2820585 ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.49372533 0.43260195 0.79298263 0.19945446]
 [0.74503838 0.87474152 0.8445648  0.79371905]
 [0.         0.         0.         0.        ]]


In [41]:
# Calculate and print the a erage reward per thousand episodes
rewards_per_thousand_episodes = np.split(
    np.array(rewards_all_episodes), num_episodes/1000)
count = 1000
print(len(rewards_all_episodes))
print("*********Average reward per thousand episodes *******\n")
print(len(rewards_per_thousand_episodes))
for r in rewards_per_thousand_episodes:
    print(r)
    print(count, ":", str(sum(r/1000)))
    count += 1000

print("\n\n**********************Q-table*******************\n")
print(q_table)


10708
*********Average reward per thousand episodes *******

1
[0. 0. 0. ... 0. 0. 0.]
1000 : 0.0


**********************Q-table*******************

[[0.53262639 0.50004396 0.51493095 0.50382742]
 [0.36556953 0.412294   0.35463159 0.48099169]
 [0.38541292 0.40051576 0.39967041 0.44173582]
 [0.31728644 0.2812601  0.24179813 0.42870357]
 [0.55624747 0.43158678 0.36051367 0.38688989]
 [0.         0.         0.         0.        ]
 [0.23025569 0.20647325 0.34585494 0.10011733]
 [0.         0.         0.         0.        ]
 [0.42533504 0.34456956 0.40662056 0.60524649]
 [0.52040307 0.67293223 0.58009831 0.44605577]
 [0.58783859 0.4248645  0.5033947  0.2820585 ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.49372533 0.43260195 0.79298263 0.19945446]
 [0.74503838 0.87474152 0.8445648  0.79371905]
 [0.         0.         0.         0.        ]]


In [42]:
# Calculate and print the a erage reward per thousand episodes
rewards_per_thousand_episodes = np.split(
    np.array(rewards_all_episodes), num_episodes/1000)
count = 1000
print(len(rewards_all_episodes))
print("*********Average reward per thousand episodes *******\n")
print(len(rewards_per_thousand_episodes))
for r in rewards_per_thousand_episodes:
    print(r)
    print(count, ":", str(sum(r/1000)))
    count += 1000

print("\n\n**********************Q-table*******************\n")
print(q_table)


10708
*********Average reward per thousand episodes *******

1
[0. 0. 0. ... 0. 0. 0.]
1000 : 0.0


**********************Q-table*******************

[[0.53262639 0.50004396 0.51493095 0.50382742]
 [0.36556953 0.412294   0.35463159 0.48099169]
 [0.38541292 0.40051576 0.39967041 0.44173582]
 [0.31728644 0.2812601  0.24179813 0.42870357]
 [0.55624747 0.43158678 0.36051367 0.38688989]
 [0.         0.         0.         0.        ]
 [0.23025569 0.20647325 0.34585494 0.10011733]
 [0.         0.         0.         0.        ]
 [0.42533504 0.34456956 0.40662056 0.60524649]
 [0.52040307 0.67293223 0.58009831 0.44605577]
 [0.58783859 0.4248645  0.5033947  0.2820585 ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.49372533 0.43260195 0.79298263 0.19945446]
 [0.74503838 0.87474152 0.8445648  0.79371905]
 [0.         0.         0.         0.        ]]


In [43]:
# Calculate and print the a erage reward per thousand episodes
rewards_per_thousand_episodes = np.split(
    np.array(rewards_all_episodes), num_episodes/1000)
count = 1000
print(len(rewards_per_thousand_episodes))
print("*********Average reward per thousand episodes *******\n")
print(len(rewards_per_thousand_episodes))
for r in rewards_per_thousand_episodes:
    print(r)
    print(count, ":", str(sum(r/1000)))
    count += 1000

print("\n\n**********************Q-table*******************\n")
print(q_table)


1
*********Average reward per thousand episodes *******

1
[0. 0. 0. ... 0. 0. 0.]
1000 : 0.0


**********************Q-table*******************

[[0.53262639 0.50004396 0.51493095 0.50382742]
 [0.36556953 0.412294   0.35463159 0.48099169]
 [0.38541292 0.40051576 0.39967041 0.44173582]
 [0.31728644 0.2812601  0.24179813 0.42870357]
 [0.55624747 0.43158678 0.36051367 0.38688989]
 [0.         0.         0.         0.        ]
 [0.23025569 0.20647325 0.34585494 0.10011733]
 [0.         0.         0.         0.        ]
 [0.42533504 0.34456956 0.40662056 0.60524649]
 [0.52040307 0.67293223 0.58009831 0.44605577]
 [0.58783859 0.4248645  0.5033947  0.2820585 ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.49372533 0.43260195 0.79298263 0.19945446]
 [0.74503838 0.87474152 0.8445648  0.79371905]
 [0.         0.         0.         0.        ]]


In [44]:
# Calculate and print the a erage reward per thousand episodes
rewards_per_thousand_episodes = np.split(
    np.array(rewards_all_episodes), num_episodes/1000)
count = 1000
print((rewards_per_thousand_episodes))
print("*********Average reward per thousand episodes *******\n")
print(len(rewards_per_thousand_episodes))
for r in rewards_per_thousand_episodes:
    print(r)
    print(count, ":", str(sum(r/1000)))
    count += 1000

print("\n\n**********************Q-table*******************\n")
print(q_table)


[array([0., 0., 0., ..., 0., 0., 0.])]
*********Average reward per thousand episodes *******

1
[0. 0. 0. ... 0. 0. 0.]
1000 : 0.0


**********************Q-table*******************

[[0.53262639 0.50004396 0.51493095 0.50382742]
 [0.36556953 0.412294   0.35463159 0.48099169]
 [0.38541292 0.40051576 0.39967041 0.44173582]
 [0.31728644 0.2812601  0.24179813 0.42870357]
 [0.55624747 0.43158678 0.36051367 0.38688989]
 [0.         0.         0.         0.        ]
 [0.23025569 0.20647325 0.34585494 0.10011733]
 [0.         0.         0.         0.        ]
 [0.42533504 0.34456956 0.40662056 0.60524649]
 [0.52040307 0.67293223 0.58009831 0.44605577]
 [0.58783859 0.4248645  0.5033947  0.2820585 ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.49372533 0.43260195 0.79298263 0.19945446]
 [0.74503838 0.87474152 0.8445648  0.79371905]
 [0.         0.         0.         0.        ]]


In [45]:
# Calculate and print the a erage reward per thousand episodes
rewards_per_thousand_episodes = np.split(\
    np.array(rewards_all_episodes), num_episodes/1000)
count = 1000
print((rewards_per_thousand_episodes))
print("*********Average reward per thousand episodes *******\n")
print(len(rewards_per_thousand_episodes))
for r in rewards_per_thousand_episodes:
    print(r)
    print(count, ":", str(sum(r/1000)))
    count += 1000

print("\n\n**********************Q-table*******************\n")
print(q_table)


[array([0., 0., 0., ..., 0., 0., 0.])]
*********Average reward per thousand episodes *******

1
[0. 0. 0. ... 0. 0. 0.]
1000 : 0.0


**********************Q-table*******************

[[0.53262639 0.50004396 0.51493095 0.50382742]
 [0.36556953 0.412294   0.35463159 0.48099169]
 [0.38541292 0.40051576 0.39967041 0.44173582]
 [0.31728644 0.2812601  0.24179813 0.42870357]
 [0.55624747 0.43158678 0.36051367 0.38688989]
 [0.         0.         0.         0.        ]
 [0.23025569 0.20647325 0.34585494 0.10011733]
 [0.         0.         0.         0.        ]
 [0.42533504 0.34456956 0.40662056 0.60524649]
 [0.52040307 0.67293223 0.58009831 0.44605577]
 [0.58783859 0.4248645  0.5033947  0.2820585 ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.49372533 0.43260195 0.79298263 0.19945446]
 [0.74503838 0.87474152 0.8445648  0.79371905]
 [0.         0.         0.         0.        ]]


In [46]:
print(len(rewards_all_episodes))

10708


In [47]:
print(len(rewards_all_episodes))
print(len(rewards_current_episode))

10708


TypeError: object of type 'float' has no len()

In [48]:
print(len(rewards_all_episodes))
print(len(rewards_per_thousand_episodes))

10708
1


In [49]:
print(len(rewards_all_episodes))
print(len(rewards_per_thousand_episodes))
type(rewards_per_thousand_episodes)

10708
1


list

In [50]:
num_episodes = 10000
# we define a maximum number of steps that our agent is allowed to take within a single episode
max_steps_per_episode = 100

# Alpha the weighted for sum of old value and learned value in Q
learning_rate = 0.01
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001


In [51]:
rewards_all_episodes = []

# Q-learning
for episode in range(num_episodes):
    state = env.reset()
    print("episodes:", episode)

    done = False
    rewards_current_episode = 0  # The start rewards
    for step in range(max_steps_per_episode):

        # Exploration-exploitation trade-off
        exploration_rate_threshold = random.uniform(0, 1)
        # this will determine whether our agent will explore or expoit
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state, :])
        else:
            action = env.action_space.sample()

        new_state, reward, done, info = env.step(action)

        # UPdate Q-table for Q(s,a)
        q_table[state, action] = q_table[state, action] * (1-learning_rate) + learning_rate*(
            reward + discount_rate * np.max(q_table[new_state, :]))

        # Transition to the next state
        state = new_state
        rewards_current_episode += reward

        if done == True:
            break

        # Exploration rate decay
        exploration_rate = min_exploration_rate + \
            (max_exploration_rate - min_exploration_rate) * \
            np.exp(-exploration_decay_rate * episode)

        rewards_all_episodes.append(rewards_current_episode)


episodes: 0
episodes: 1
episodes: 2
episodes: 3
episodes: 4
episodes: 5
episodes: 6
episodes: 7
episodes: 8
episodes: 9
episodes: 10
episodes: 11
episodes: 12
episodes: 13
episodes: 14
episodes: 15
episodes: 16
episodes: 17
episodes: 18
episodes: 19
episodes: 20
episodes: 21
episodes: 22
episodes: 23
episodes: 24
episodes: 25
episodes: 26
episodes: 27
episodes: 28
episodes: 29
episodes: 30
episodes: 31
episodes: 32
episodes: 33
episodes: 34
episodes: 35
episodes: 36
episodes: 37
episodes: 38
episodes: 39
episodes: 40
episodes: 41
episodes: 42
episodes: 43
episodes: 44
episodes: 45
episodes: 46
episodes: 47
episodes: 48
episodes: 49
episodes: 50
episodes: 51
episodes: 52
episodes: 53
episodes: 54
episodes: 55
episodes: 56
episodes: 57
episodes: 58
episodes: 59
episodes: 60
episodes: 61
episodes: 62
episodes: 63
episodes: 64
episodes: 65
episodes: 66
episodes: 67
episodes: 68
episodes: 69
episodes: 70
episodes: 71
episodes: 72
episodes: 73
episodes: 74
episodes: 75
episodes: 76
episodes:

In [52]:
# Calculate and print the a erage reward per thousand episodes
rewards_per_thousand_episodes = np.split(
    np.array(rewards_all_episodes), num_episodes/1000)
count = 1000
print((rewards_per_thousand_episodes))
print("*********Average reward per thousand episodes *******\n")
print(len(rewards_per_thousand_episodes))
for r in rewards_per_thousand_episodes:
    print(r)
    print(count, ":", str(sum(r/1000)))
    count += 1000

print("\n\n**********************Q-table*******************\n")
print(q_table)


ValueError: array split does not result in an equal division

In [53]:
print(len(rewards_all_episodes))

352406


In [54]:
rewards_all_episodes = []

# Q-learning
for episode in range(num_episodes):
    state = env.reset()
    print("episodes:", episode, len(rewards_all_episodes))

    done = False
    rewards_current_episode = 0  # The start rewards
    for step in range(max_steps_per_episode):

        # Exploration-exploitation trade-off
        exploration_rate_threshold = random.uniform(0, 1)
        # this will determine whether our agent will explore or expoit
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state, :])
        else:
            action = env.action_space.sample()

        new_state, reward, done, info = env.step(action)

        # UPdate Q-table for Q(s,a)
        q_table[state, action] = q_table[state, action] * (1-learning_rate) + learning_rate*(
            reward + discount_rate * np.max(q_table[new_state, :]))

        # Transition to the next state
        state = new_state
        rewards_current_episode += reward

        if done == True:
            break

        # Exploration rate decay
        exploration_rate = min_exploration_rate + \
            (max_exploration_rate - min_exploration_rate) * \
            np.exp(-exploration_decay_rate * episode)

        rewards_all_episodes.append(rewards_current_episode)


episodes: 0 0
episodes: 1 4
episodes: 2 8
episodes: 3 13
episodes: 4 21
episodes: 5 22
episodes: 6 23
episodes: 7 27
episodes: 8 28
episodes: 9 52
episodes: 10 57
episodes: 11 73
episodes: 12 78
episodes: 13 80
episodes: 14 86
episodes: 15 97
episodes: 16 104
episodes: 17 109
episodes: 18 112
episodes: 19 121
episodes: 20 122
episodes: 21 130
episodes: 22 133
episodes: 23 143
episodes: 24 146
episodes: 25 156
episodes: 26 187
episodes: 27 188
episodes: 28 189
episodes: 29 193
episodes: 30 194
episodes: 31 197
episodes: 32 200
episodes: 33 212
episodes: 34 213
episodes: 35 228
episodes: 36 240
episodes: 37 253
episodes: 38 259
episodes: 39 264
episodes: 40 274
episodes: 41 276
episodes: 42 279
episodes: 43 283
episodes: 44 309
episodes: 45 319
episodes: 46 322
episodes: 47 326
episodes: 48 333
episodes: 49 339
episodes: 50 366
episodes: 51 367
episodes: 52 370
episodes: 53 387
episodes: 54 398
episodes: 55 409
episodes: 56 442
episodes: 57 449
episodes: 58 453
episodes: 59 463
episodes:

In [55]:
rewards_all_episodes = []

# Q-learning
for episode in range(num_episodes):
    state = env.reset()
    print("episodes:", episode, len(rewards_all_episodes))

    done = False
    rewards_current_episode = 0  # The start rewards
    for step in range(max_steps_per_episode):

        # Exploration-exploitation trade-off
        exploration_rate_threshold = random.uniform(0, 1)
        # this will determine whether our agent will explore or expoit
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state, :])
        else:
            action = env.action_space.sample()

        new_state, reward, done, info = env.step(action)

        # UPdate Q-table for Q(s,a)
        q_table[state, action] = q_table[state, action] * (1-learning_rate) + learning_rate*(
            reward + discount_rate * np.max(q_table[new_state, :]))

        # Transition to the next state
        state = new_state
        rewards_current_episode += reward

        if done == True:
            break

    # Exploration rate decay
    exploration_rate = min_exploration_rate + \
        (max_exploration_rate - min_exploration_rate) * \
        np.exp(-exploration_decay_rate * episode)

    rewards_all_episodes.append(rewards_current_episode)


episodes: 0 0
episodes: 1 1
episodes: 2 2
episodes: 3 3
episodes: 4 4
episodes: 5 5
episodes: 6 6
episodes: 7 7
episodes: 8 8
episodes: 9 9
episodes: 10 10
episodes: 11 11
episodes: 12 12
episodes: 13 13
episodes: 14 14
episodes: 15 15
episodes: 16 16
episodes: 17 17
episodes: 18 18
episodes: 19 19
episodes: 20 20
episodes: 21 21
episodes: 22 22
episodes: 23 23
episodes: 24 24
episodes: 25 25
episodes: 26 26
episodes: 27 27
episodes: 28 28
episodes: 29 29
episodes: 30 30
episodes: 31 31
episodes: 32 32
episodes: 33 33
episodes: 34 34
episodes: 35 35
episodes: 36 36
episodes: 37 37
episodes: 38 38
episodes: 39 39
episodes: 40 40
episodes: 41 41
episodes: 42 42
episodes: 43 43
episodes: 44 44
episodes: 45 45
episodes: 46 46
episodes: 47 47
episodes: 48 48
episodes: 49 49
episodes: 50 50
episodes: 51 51
episodes: 52 52
episodes: 53 53
episodes: 54 54
episodes: 55 55
episodes: 56 56
episodes: 57 57
episodes: 58 58
episodes: 59 59
episodes: 60 60
episodes: 61 61
episodes: 62 62
episodes: 63

In [56]:
# Calculate and print the a erage reward per thousand episodes
rewards_per_thousand_episodes = np.split(
    np.array(rewards_all_episodes), num_episodes/1000)
count = 1000
print((rewards_per_thousand_episodes))
print("*********Average reward per thousand episodes *******\n")
print(len(rewards_per_thousand_episodes))
for r in rewards_per_thousand_episodes:
    print(r)
    print(count, ":", str(sum(r/1000)))
    count += 1000

print("\n\n**********************Q-table*******************\n")
print(q_table)


[array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0

In [57]:
# Calculate and print the a erage reward per thousand episodes
rewards_per_thousand_episodes = np.split(
    np.array(rewards_all_episodes), num_episodes/1000)
count = 1000
print("*********Average reward per thousand episodes *******\n")
for r in rewards_per_thousand_episodes:
    print(count, ":", str(sum(r/1000)))
    count += 1000

print("\n\n**********************Q-table*******************\n")
print(q_table)


*********Average reward per thousand episodes *******

1000 : 0.04300000000000003
2000 : 0.23100000000000018
3000 : 0.4220000000000003
4000 : 0.5760000000000004
5000 : 0.6490000000000005
6000 : 0.6750000000000005
7000 : 0.6980000000000005
8000 : 0.7020000000000005
9000 : 0.7150000000000005
10000 : 0.6790000000000005


**********************Q-table*******************

[[0.53221436 0.52265765 0.52280057 0.52204182]
 [0.35542174 0.34351652 0.30963065 0.49768833]
 [0.43166671 0.43842186 0.42496342 0.47629717]
 [0.29098011 0.29984157 0.2873807  0.46519218]
 [0.55051947 0.41012567 0.39518974 0.34971295]
 [0.         0.         0.         0.        ]
 [0.31705875 0.22740345 0.35478128 0.14017236]
 [0.         0.         0.         0.        ]
 [0.38106869 0.40942071 0.38106202 0.58647281]
 [0.42501849 0.62811513 0.43778402 0.39596083]
 [0.6029513  0.51042618 0.37535163 0.33007896]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.48138923 0.5977

 ### Watch the agent play the game

In [58]:
for episode in range(10):
    # initialize new episode params
    state = env.reset()
    done = False
    print("*******EPISODE ",episode +1, "**********\n\n\n\n\n")
    time.sleep(1)
    for step in range(max_steps_per_episode):
        clear_output(wait = True)
        env.render() # render the current state of the environment to display
        # Show the current state of environment on screen
        # Choose action with highest Q-value for current state
        # Take new action
        action = np.argmax(q_table[state,:])
        new_state, reward, done, info = env.step(action)
        
        state = new_state

        if done:
            clear_output(wait = True)
            env.render()
            if reward == 1:
                # Agent reached the goak and won episode
                print("**** You reached the goal****")
                time.sleep(3)
            else:
                # Agent stepped in a hole and lost episode
                print("***** fell into a hole****")
                time.sleep(3)
                clear_output(wait = True)
    break
env.close


*******EPISODE  1 **********







TypeError: 'module' object is not callable

 ### Watch the agent play the game

In [59]:
for episode in range(10):
    # initialize new episode params
    state = env.reset()
    done = False
    print("*******EPISODE ",episode +1, "**********\n\n\n\n\n")
    time.sleep(1)
    for step in range(max_steps_per_episode):
        #clear_output(wait = True)
        env.render() # render the current state of the environment to display
        # Show the current state of environment on screen
        # Choose action with highest Q-value for current state
        # Take new action
        action = np.argmax(q_table[state,:])
        new_state, reward, done, info = env.step(action)
        
        state = new_state

        if done:
            clear_output(wait = True)
            env.render()
            if reward == 1:
                # Agent reached the goak and won episode
                print("**** You reached the goal****")
                time.sleep(3)
            else:
                # Agent stepped in a hole and lost episode
                print("***** fell into a hole****")
                time.sleep(3)
                clear_output(wait = True)
    break
env.close


*******EPISODE  1 **********






SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG


TypeError: 'module' object is not callable

 ### Watch the agent play the game

In [61]:
for episode in range(10):
    # initialize new episode params
    state = env.reset()
    done = False
    print("*******EPISODE ",episode +1, "**********\n\n\n\n\n")
    time.sleep(1)
    for step in range(max_steps_per_episode):
        #clear_output(wait = True)
        env.render() # render the current state of the environment to display
        # Show the current state of environment on screen
        # Choose action with highest Q-value for current state
        # Take new action
        action = np.argmax(q_table[state,:])
        new_state, reward, done, info = env.step(action)
        
        state = new_state

        if done:
            #clear_output(wait = True)
            env.render()
            if reward == 1:
                # Agent reached the goak and won episode
                print("**** You reached the goal****")
                time.sleep(3)
            else:
                # Agent stepped in a hole and lost episode
                print("***** fell into a hole****")
                time.sleep(3)
    break
env.close


*******EPISODE  1 **********






SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HF

<bound method Wrapper.close of <TimeLimit<FrozenLakeEnv<FrozenLake-v0>>>>

In [62]:
for episode in range(3):
    # initialize new episode params
    state = env.reset()
    done = False
    print("*******EPISODE ", episode + 1, "**********\n\n\n\n\n")
    time.sleep(1)
    for step in range(max_steps_per_episode):
        #clear_output(wait = True)
        env.render()  # render the current state of the environment to display
        # Show the current state of environment on screen
        # Choose action with highest Q-value for current state
        # Take new action
        action = np.argmax(q_table[state, :])
        new_state, reward, done, info = env.step(action)

        state = new_state

        if done:
            #clear_output(wait = True)
            env.render()
            if reward == 1:
                # Agent reached the goak and won episode
                print("**** You reached the goal****")
                time.sleep(3)
            else:
                # Agent stepped in a hole and lost episode
                print("***** fell into a hole****")
                time.sleep(3)
    break
env.close


*******EPISODE  1 **********






SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
**** You reached the goal****
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
***** fell into a hole****
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FH