In [1]:
import numpy as np
import gym 
import random
import time
import IPython.display as clear_output

Load the environment

In [2]:
env = gym.make("FrozenLake-v0")

In [3]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size,action_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [22]:
num_episodes = 1000
max_steps_per_episode = 100

learning_rate = 0.01            # Alpha
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.01

###  Implement Reinforcement learning

In [36]:
rewards_all_episodes = []

# Q-learning
for episode in range(num_episodes):
    state = env.reset()
    
    done = False
    rewards_current_episode = 0 # The start rewards
    for step in range(max_steps_per_episode):
        
        #Exploration-exploitation trade-off
        exploration_rate_threshold = random.uniform(0,1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state,:])
        else:
            action = env.action_space.sample()
        
        new_state,reward, done, info = env.step(action)
        
        # UPdate Q-table for Q(s,a)
        q_table[state, action] = q_table[state,action] * (1-learning_rate) + \
                            learning_rate*(reward + discount_rate * np.max(q_table[new_state,:]))
       
                                                                       
        state = new_state
        rewards_current_episode += reward
                                                                                                
        if done == True:
            break
        
        # Exploration rate decay
        exploration_rate = min_exploration_rate +\
                          (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate * episode)
                           
        rewards_all_episodes.append(rewards_current_episode)    
                           
# Calculate and print the a erage reward per thousand episodes
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes), num_episodes/1000)
count = 1000
                           
print("*********Average reward per thousand episodes *******\n")
for r in rewards_per_thousand_episodes:
    print(count, ":", str(sum(r/1000) ) )
    count+= 1000
                           
print("\n\n**********************Q-table*******************\n")
print(q_table)

*********Average reward per thousand episodes *******

1000 : 0.0


**********************Q-table*******************

[[8.05645142e-03 4.04990755e-03 3.71387870e-03 4.06183599e-03]
 [8.77010083e-04 8.73886628e-04 2.89081271e-04 2.61501339e-03]
 [1.52614377e-03 3.27423878e-04 1.10073235e-04 1.61692691e-04]
 [1.72220383e-05 1.67034503e-05 1.94747505e-06 7.85367816e-05]
 [4.40265291e-03 2.98166029e-03 8.10708120e-03 2.06362528e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [7.63051544e-04 4.29686994e-03 1.14381457e-03 1.25382073e-05]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.92070630e-03 3.59542665e-03 1.60497219e-02 5.20935343e-03]
 [3.90401545e-02 6.06932918e-03 3.28384824e-03 1.64823596e-03]
 [1.37034844e-02 6.16655859e-03 3.90268075e-02 3.22198126e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.55024334e-03 1.41616925e-02 1.50993844e-02 1.39810983e-01]
